
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto1_servidor;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 18;
  public static final int DISTINTO = 43;
  public static final int CHAR = 37;
  public static final int CASE = 28;
  public static final int DOUBLE = 39;
  public static final int PRIVATE = 33;
  public static final int INT = 38;
  public static final int PUNTOCOMA = 13;
  public static final int OUT = 55;
  public static final int FOR = 26;
  public static final int IDENTIFICADOR = 47;
  public static final int NOT = 46;
  public static final int AND = 44;
  public static final int MENORIGUAL = 3;
  public static final int ELSEIF = 50;
  public static final int IGUAL = 6;
  public static final int OR = 45;
  public static final int OBJECT = 41;
  public static final int CLASS = 31;
  public static final int INCREMENTO = 58;
  public static final int IF = 22;
  public static final int MAYORIGUAL = 2;
  public static final int BOOLEAN = 36;
  public static final int EOF = 0;
  public static final int SYSTEM = 53;
  public static final int RETURN = 30;
  public static final int DECREMENTO = 59;
  public static final int NEW = 54;
  public static final int error = 1;
  public static final int DIGITO = 48;
  public static final int COMA = 12;
  public static final int CADENA = 49;
  public static final int COMENTARIO = 57;
  public static final int MENOS = 8;
  public static final int MENOR = 5;
  public static final int BREAK = 29;
  public static final int VOID = 60;
  public static final int SWITCH = 25;
  public static final int MAYOR = 4;
  public static final int IMPORT = 21;
  public static final int DIGITONEG = 56;
  public static final int ELSE = 23;
  public static final int PROTECTED = 34;
  public static final int PUNTO = 11;
  public static final int IGUALIGUAL = 42;
  public static final int FINAL = 35;
  public static final int WHILE = 24;
  public static final int DEFAULT = 51;
  public static final int PUBLIC = 32;
  public static final int PARC = 17;
  public static final int STRING = 40;
  public static final int PARA = 16;
  public static final int CORC = 15;
  public static final int CORA = 14;
  public static final int DIVISION = 9;
  public static final int LLAVEC = 20;
  public static final int LLAVEA = 19;
  public static final int PRINT = 52;
  public static final int DO = 27;
  public static final int MULTIPLICACION = 10;
  public static final int MAS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAYORIGUAL",
  "MENORIGUAL",
  "MAYOR",
  "MENOR",
  "IGUAL",
  "MAS",
  "MENOS",
  "DIVISION",
  "MULTIPLICACION",
  "PUNTO",
  "COMA",
  "PUNTOCOMA",
  "CORA",
  "CORC",
  "PARA",
  "PARC",
  "DOSPUNTOS",
  "LLAVEA",
  "LLAVEC",
  "IMPORT",
  "IF",
  "ELSE",
  "WHILE",
  "SWITCH",
  "FOR",
  "DO",
  "CASE",
  "BREAK",
  "RETURN",
  "CLASS",
  "PUBLIC",
  "PRIVATE",
  "PROTECTED",
  "FINAL",
  "BOOLEAN",
  "CHAR",
  "INT",
  "DOUBLE",
  "STRING",
  "OBJECT",
  "IGUALIGUAL",
  "DISTINTO",
  "AND",
  "OR",
  "NOT",
  "IDENTIFICADOR",
  "DIGITO",
  "CADENA",
  "ELSEIF",
  "DEFAULT",
  "PRINT",
  "SYSTEM",
  "NEW",
  "OUT",
  "DIGITONEG",
  "COMENTARIO",
  "INCREMENTO",
  "DECREMENTO",
  "VOID"
  };
}

