
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package practica1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 56;
  public static final int CLOSEPA = 59;
  public static final int FUNCTION = 20;
  public static final int READLINE = 16;
  public static final int CHAR = 45;
  public static final int CASE = 35;
  public static final int DIFERENTE = 2;
  public static final int INTEGER = 47;
  public static final int DOUBLE = 46;
  public static final int PRIVATE = 41;
  public static final int FOR = 27;
  public static final int STATIC = 43;
  public static final int NOT = 38;
  public static final int AND = 36;
  public static final int MENORIGUAL = 4;
  public static final int IGUAL = 7;
  public static final int ELSELF = 25;
  public static final int OR = 37;
  public static final int OPENPA = 58;
  public static final int UNTIL = 33;
  public static final int SELECT = 34;
  public static final int EXIT = 39;
  public static final int NEXT = 30;
  public static final int LOOP = 32;
  public static final int IF = 22;
  public static final int ID = 55;
  public static final int MAYORIGUAL = 3;
  public static final int BOOLEAN = 44;
  public static final int DIM = 42;
  public static final int EOF = 0;
  public static final int RETURN = 21;
  public static final int BYVAL = 19;
  public static final int error = 1;
  public static final int COMA = 50;
  public static final int CADENA = 57;
  public static final int MENOS = 9;
  public static final int MENOR = 6;
  public static final int CONCATENAR = 54;
  public static final int MAYOR = 5;
  public static final int MODULE = 12;
  public static final int WRITELINE = 17;
  public static final int ELSE = 23;
  public static final int PUNTO = 51;
  public static final int TO = 28;
  public static final int WHILE = 26;
  public static final int PUBLIC = 40;
  public static final int THEN = 24;
  public static final int OPEN = 52;
  public static final int END = 13;
  public static final int LONG = 48;
  public static final int STRING = 49;
  public static final int CLOSE = 53;
  public static final int AS = 14;
  public static final int DIVISION = 10;
  public static final int SUB = 18;
  public static final int DO = 31;
  public static final int CONSOLE = 15;
  public static final int STEP = 29;
  public static final int MULTIPLICACION = 11;
  public static final int MAS = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DIFERENTE",
  "MAYORIGUAL",
  "MENORIGUAL",
  "MAYOR",
  "MENOR",
  "IGUAL",
  "MAS",
  "MENOS",
  "DIVISION",
  "MULTIPLICACION",
  "MODULE",
  "END",
  "AS",
  "CONSOLE",
  "READLINE",
  "WRITELINE",
  "SUB",
  "BYVAL",
  "FUNCTION",
  "RETURN",
  "IF",
  "ELSE",
  "THEN",
  "ELSELF",
  "WHILE",
  "FOR",
  "TO",
  "STEP",
  "NEXT",
  "DO",
  "LOOP",
  "UNTIL",
  "SELECT",
  "CASE",
  "AND",
  "OR",
  "NOT",
  "EXIT",
  "PUBLIC",
  "PRIVATE",
  "DIM",
  "STATIC",
  "BOOLEAN",
  "CHAR",
  "DOUBLE",
  "INTEGER",
  "LONG",
  "STRING",
  "COMA",
  "PUNTO",
  "OPEN",
  "CLOSE",
  "CONCATENAR",
  "ID",
  "NUMERO",
  "CADENA",
  "OPENPA",
  "CLOSEPA"
  };
}

