
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto1_cliente;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TD = 10;
  public static final int COMILLAS = 32;
  public static final int ACOLOR = 33;
  public static final int IDENTIFICADOR = 40;
  public static final int DIVISION = 36;
  public static final int CLOSEHTML = 3;
  public static final int CLOSEP = 25;
  public static final int CLOSE = 56;
  public static final int CLOSETH = 21;
  public static final int CLOSETD = 22;
  public static final int CA3 = 77;
  public static final int CLOSEH = 18;
  public static final int TABLE = 8;
  public static final int MAYOR = 37;
  public static final int DOUBLE = 51;
  public static final int FONT = 30;
  public static final int DISTINTO = 68;
  public static final int NOT = 70;
  public static final int COMENTARIO = 39;
  public static final int IGUALIGUAL = 67;
  public static final int FLOAT = 57;
  public static final int PARC = 45;
  public static final int PARA = 44;
  public static final int INCREMENTO = 71;
  public static final int CLOSEBODY = 17;
  public static final int COMA = 47;
  public static final int DIGITO = 41;
  public static final int MODULO = 64;
  public static final int IGUAL = 31;
  public static final int CLASE = 86;
  public static final int RESULT = 54;
  public static final int CLOSEHEAD = 16;
  public static final int TIPO = 85;
  public static final int CHAR = 78;
  public static final int ALIGN = 29;
  public static final int DECIMAL = 59;
  public static final int NOMBRE = 81;
  public static final int BOOLEAN = 58;
  public static final int DOSPUNTOS = 49;
  public static final int SIMBOLO = 75;
  public static final int DECREMENTO = 72;
  public static final int DIV = 12;
  public static final int P = 13;
  public static final int MENOS = 62;
  public static final int MENOR = 38;
  public static final int MAS = 61;
  public static final int INT = 53;
  public static final int CLOSETITLE = 19;
  public static final int H = 6;
  public static final int EOF = 0;
  public static final int PUNTO = 46;
  public static final int CLASES = 84;
  public static final int PRINT = 73;
  public static final int MENORIGUAL = 66;
  public static final int BODY = 5;
  public static final int TITLE = 7;
  public static final int OR = 74;
  public static final int error = 1;
  public static final int HEAD = 4;
  public static final int CLOSEDIV = 24;
  public static final int TEXTCOLOR = 34;
  public static final int PARAMETROS = 88;
  public static final int MULTIPLICACION = 63;
  public static final int VARIABLES = 80;
  public static final int PUNTOCOMA = 48;
  public static final int BR = 15;
  public static final int CANTIDAD = 82;
  public static final int DIGITONEG = 43;
  public static final int DOLAR = 50;
  public static final int HR = 14;
  public static final int CADENA = 42;
  public static final int MAYORIGUAL = 65;
  public static final int STRING = 52;
  public static final int ALINEACION = 35;
  public static final int METODOS = 83;
  public static final int CLOSEBR = 27;
  public static final int APOS = 60;
  public static final int TR = 11;
  public static final int CADENA2 = 76;
  public static final int CLOSEHR = 26;
  public static final int AND = 69;
  public static final int OPEN = 55;
  public static final int COLORES = 28;
  public static final int LINEAS = 87;
  public static final int SCORE = 79;
  public static final int CLOSETABLE = 20;
  public static final int OPENHTML = 2;
  public static final int TH = 9;
  public static final int CLOSETR = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPENHTML",
  "CLOSEHTML",
  "HEAD",
  "BODY",
  "H",
  "TITLE",
  "TABLE",
  "TH",
  "TD",
  "TR",
  "DIV",
  "P",
  "HR",
  "BR",
  "CLOSEHEAD",
  "CLOSEBODY",
  "CLOSEH",
  "CLOSETITLE",
  "CLOSETABLE",
  "CLOSETH",
  "CLOSETD",
  "CLOSETR",
  "CLOSEDIV",
  "CLOSEP",
  "CLOSEHR",
  "CLOSEBR",
  "COLORES",
  "ALIGN",
  "FONT",
  "IGUAL",
  "COMILLAS",
  "ACOLOR",
  "TEXTCOLOR",
  "ALINEACION",
  "DIVISION",
  "MAYOR",
  "MENOR",
  "COMENTARIO",
  "IDENTIFICADOR",
  "DIGITO",
  "CADENA",
  "DIGITONEG",
  "PARA",
  "PARC",
  "PUNTO",
  "COMA",
  "PUNTOCOMA",
  "DOSPUNTOS",
  "DOLAR",
  "DOUBLE",
  "STRING",
  "INT",
  "RESULT",
  "OPEN",
  "CLOSE",
  "FLOAT",
  "BOOLEAN",
  "DECIMAL",
  "APOS",
  "MAS",
  "MENOS",
  "MULTIPLICACION",
  "MODULO",
  "MAYORIGUAL",
  "MENORIGUAL",
  "IGUALIGUAL",
  "DISTINTO",
  "AND",
  "NOT",
  "INCREMENTO",
  "DECREMENTO",
  "PRINT",
  "OR",
  "SIMBOLO",
  "CADENA2",
  "CA3",
  "CHAR",
  "SCORE",
  "VARIABLES",
  "NOMBRE",
  "CANTIDAD",
  "METODOS",
  "CLASES",
  "TIPO",
  "CLASE",
  "LINEAS",
  "PARAMETROS"
  };
}

