
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package examenfinal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INVERS = 62;
  public static final int DOSPUNTOS = 18;
  public static final int DISTINTO = 22;
  public static final int DIFERENCIA = 30;
  public static final int POT = 61;
  public static final int CHAR = 32;
  public static final int DIBUJAREXP = 52;
  public static final int MOSTRAR = 50;
  public static final int SI = 41;
  public static final int XOR = 26;
  public static final int DIBUJARAST = 51;
  public static final int DOUBLE = 34;
  public static final int PORCENTAJE = 29;
  public static final int INT = 33;
  public static final int PUNTOCOMA = 13;
  public static final int HASTA = 46;
  public static final int PRINCIPAL = 40;
  public static final int IDENTIFICADOR = 55;
  public static final int NOT = 25;
  public static final int MENORIGUAL = 3;
  public static final int AND = 23;
  public static final int IGUAL = 6;
  public static final int SINO = 42;
  public static final int OR = 24;
  public static final int DIBUJARTS = 53;
  public static final int MIENTRAS = 47;
  public static final int BOOL = 31;
  public static final int PARAB = 45;
  public static final int CONTINUAR = 49;
  public static final int INCREMENTO = 27;
  public static final int IMPORTAR = 37;
  public static final int ID = 59;
  public static final int RETORNO = 39;
  public static final int MAYORIGUAL = 2;
  public static final int DECIMAL = 58;
  public static final int EOF = 0;
  public static final int DECREMENTO = 28;
  public static final int error = 1;
  public static final int DIGITO = 56;
  public static final int COMA = 12;
  public static final int CADENA = 57;
  public static final int COMENTARIO = 54;
  public static final int MENOS = 8;
  public static final int MENOR = 5;
  public static final int MAYOR = 4;
  public static final int SELECCIONA = 43;
  public static final int DETENER = 48;
  public static final int PUNTO = 11;
  public static final int VACIO = 36;
  public static final int IGUALIGUAL = 21;
  public static final int PARC = 17;
  public static final int STRING = 35;
  public static final int PARA = 16;
  public static final int DEFINIR = 38;
  public static final int CORC = 15;
  public static final int CORA = 14;
  public static final int DIVISION = 9;
  public static final int LLAVEC = 20;
  public static final int APOSTROFE = 60;
  public static final int DEFECTO = 44;
  public static final int LLAVEA = 19;
  public static final int MULTIPLICACION = 10;
  public static final int MAS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAYORIGUAL",
  "MENORIGUAL",
  "MAYOR",
  "MENOR",
  "IGUAL",
  "MAS",
  "MENOS",
  "DIVISION",
  "MULTIPLICACION",
  "PUNTO",
  "COMA",
  "PUNTOCOMA",
  "CORA",
  "CORC",
  "PARA",
  "PARC",
  "DOSPUNTOS",
  "LLAVEA",
  "LLAVEC",
  "IGUALIGUAL",
  "DISTINTO",
  "AND",
  "OR",
  "NOT",
  "XOR",
  "INCREMENTO",
  "DECREMENTO",
  "PORCENTAJE",
  "DIFERENCIA",
  "BOOL",
  "CHAR",
  "INT",
  "DOUBLE",
  "STRING",
  "VACIO",
  "IMPORTAR",
  "DEFINIR",
  "RETORNO",
  "PRINCIPAL",
  "SI",
  "SINO",
  "SELECCIONA",
  "DEFECTO",
  "PARAB",
  "HASTA",
  "MIENTRAS",
  "DETENER",
  "CONTINUAR",
  "MOSTRAR",
  "DIBUJARAST",
  "DIBUJAREXP",
  "DIBUJARTS",
  "COMENTARIO",
  "IDENTIFICADOR",
  "DIGITO",
  "CADENA",
  "DECIMAL",
  "ID",
  "APOSTROFE",
  "POT",
  "INVERS"
  };
}

