/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef servidor_CONSTANTS_H
#define servidor_CONSTANTS_H

#include "servidor_types.h"

namespace proyecto1 {

class servidorConstants {
 public:
  servidorConstants();

};

extern const servidorConstants g_servidor_constants;

} // namespace

#endif
