// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it
/*
#include "Proyecto1.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::proyecto1;

class Proyecto1Handler : virtual public Proyecto1If {
 public:
  Proyecto1Handler() {
    // Your initialization goes here
  }

  bool accesoNivel(const int32_t num1) {
    // Your implementation goes here
    printf("accesoNivel\n");
  }

  void generadorEnemigos() {
    // Your implementation goes here
    printf("generadorEnemigos\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<Proyecto1Handler> handler(new Proyecto1Handler());
  shared_ptr<TProcessor> processor(new Proyecto1Processor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}
*/
