/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "servidor_constants.h"

namespace proyecto1 {

const servidorConstants g_servidor_constants;

servidorConstants::servidorConstants() {
}

} // namespace

