//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWeb.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/guardarImagen", ReplyAction="http://tempuri.org/IService/guardarImagenResponse")]
        string guardarImagen(byte[] f, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/guardarImagen", ReplyAction="http://tempuri.org/IService/guardarImagenResponse")]
        System.Threading.Tasks.Task<string> guardarImagenAsync(byte[] f, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getImagenes", ReplyAction="http://tempuri.org/IService/getImagenesResponse")]
        byte[] getImagenes(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getImagenes", ReplyAction="http://tempuri.org/IService/getImagenesResponse")]
        System.Threading.Tasks.Task<byte[]> getImagenesAsync(string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ClienteWeb.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ClienteWeb.ServiceReference1.IService>, ClienteWeb.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string guardarImagen(byte[] f, string fileName) {
            return base.Channel.guardarImagen(f, fileName);
        }
        
        public System.Threading.Tasks.Task<string> guardarImagenAsync(byte[] f, string fileName) {
            return base.Channel.guardarImagenAsync(f, fileName);
        }
        
        public byte[] getImagenes(string fileName) {
            return base.Channel.getImagenes(fileName);
        }
        
        public System.Threading.Tasks.Task<byte[]> getImagenesAsync(string fileName) {
            return base.Channel.getImagenesAsync(fileName);
        }
    }
}
